from hash_1 import *

def tests():
    table = HashTable(5)
    table.hashAdd("town")
    table.hashAdd("rather")
    table.hashAdd("short")
    table.hashAdd("toward")
    table.hashAdd("employee")
    table.hashAdd("player")
    table.hashAdd("toward")
    table.hashAdd("the")
    table.hashAdd("of")
    table.hashAdd("college")
    table.hashAdd("in")
    table.hashAdd("yes")
    table.hashAdd("billion")
    table.hashAdd("five")
    table.hashAdd("wear")
    table.hashAdd("last")
    table.hashAdd("decade")
    table.hashAdd("first")
    table.hashAdd("training")
    table.hashAdd("friend")
    table.print()
    table.remove("employee")
    table.remove("of")
    table.remove("toward")
    table.remove("in")
    table.remove("player")
    table.remove("town")
    table.remove("five")
    table.remove("rather")
    table.remove("yes")
    table.print()
    table.search("in")
    table.search(1)